import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} space-y-4 sm:m-4 dark:dark:bg-gray-800`}
      >
        <Header />
        <main className="flex min-h-screen flex-col sm:px-4 bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
